# Generated by Django 5.2.5 on 2026-03-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrito',
            field=models.TextField(default='{}'),
        ),
    ]
