# Generated by Django 5.2.5 on 2025-10-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
